### ISSUE TITLE
Top K pixels gradient backpropagation

### ISSUE THREAD

**Issue by kudou-reira** [vcg-uvic/lf-net-release#16]
![image](https://user-images.githubusercontent.com/26351130/64393705-a0e77400-d08d-11e9-94a7-960c6e815956.png)
https://github.com/vcg-uvic/lf-net-release/blob/ab436517544f716a3f3de90f33e29db1020fca2f/inference.py#L197

In the code, the gradients of the top _K_ pixels are stopped, but in the paper, the opposite is stated.

**Comment by xyukiono** [comment]
As you pointed out, top-k function itself is non-differentiable so that we explicitly stop the gradient from it. 

Instead of that, we actually obtain gradients from keypoint subpixel estimation part. 
https://github.com/vcg-uvic/lf-net-release/blob/master/inference.py#L123

If soft_kpts is True, patches around keypoints are cropped from heatmap and compute subpixel locations by using soft-argmax, which is differentiable, and gradients will flow back from subpixel computation to heatmap.

Sorry let you confuse.

**Comment by kmyid** [comment]
Hmmm I was hoping to have a clearer and strategic response. But oh well. :-)

Message written with iPhone. 
Please excuse any brievity and typos.
_________  

Kwang Moo YI
Assistant Professor
Dept. of Computer Science
University of Victoria
+1 (250) 475 5837

**Comment by kmyid** [comment]
I think the description of this part is confusing. We probably should update the text for at least the arXiv version.

**Comment by kudou-reira** [comment]
Thank you, I understand how it works now.
